use std::collections::{BTreeSet, VecDeque};
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime};

use crate::error::{RebeccaError, Result};
use crate::model::DEFAULT_PROJECT_ARTIFACT_MAX_DEPTH;
use crate::scan::ScanCancellationToken;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProjectArtifactDefinition {
    pub directory_name: &'static str,
    pub rule_id: &'static str,
    pub restore_hint: &'static str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProjectArtifactCandidate {
    pub definition: ProjectArtifactDefinition,
    pub path: PathBuf,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProjectArtifactScanOptions {
    pub roots: Vec<PathBuf>,
    pub max_depth: usize,
}

impl ProjectArtifactScanOptions {
    pub fn new(roots: Vec<PathBuf>) -> Self {
        Self {
            roots,
            max_depth: DEFAULT_PROJECT_ARTIFACT_MAX_DEPTH,
        }
    }

    pub fn with_max_depth(mut self, max_depth: usize) -> Self {
        self.max_depth = max_depth;
        self
    }
}

const PROJECT_ARTIFACT_DEFINITIONS: &[ProjectArtifactDefinition] = &[
    ProjectArtifactDefinition {
        directory_name: "node_modules",
        rule_id: "windows.project-artifact-node-modules",
        restore_hint: "Dependencies can be restored with the project's package manager.",
    },
    ProjectArtifactDefinition {
        directory_name: "target",
        rule_id: "windows.project-artifact-target",
        restore_hint: "Build outputs can be regenerated by the project build tool.",
    },
    ProjectArtifactDefinition {
        directory_name: "build",
        rule_id: "windows.project-artifact-build",
        restore_hint: "Build outputs can be regenerated by the project build tool.",
    },
    ProjectArtifactDefinition {
        directory_name: "dist",
        rule_id: "windows.project-artifact-dist",
        restore_hint: "Distribution outputs can be regenerated by the project build tool.",
    },
    ProjectArtifactDefinition {
        directory_name: "venv",
        rule_id: "windows.project-artifact-python-venv",
        restore_hint: "Python virtual environments can be recreated from project dependencies.",
    },
    ProjectArtifactDefinition {
        directory_name: ".venv",
        rule_id: "windows.project-artifact-python-venv",
        restore_hint: "Python virtual environments can be recreated from project dependencies.",
    },
    ProjectArtifactDefinition {
        directory_name: ".pytest_cache",
        rule_id: "windows.project-artifact-pytest-cache",
        restore_hint: "Pytest cache data is rebuildable.",
    },
    ProjectArtifactDefinition {
        directory_name: ".mypy_cache",
        rule_id: "windows.project-artifact-mypy-cache",
        restore_hint: "Mypy cache data is rebuildable.",
    },
    ProjectArtifactDefinition {
        directory_name: ".tox",
        rule_id: "windows.project-artifact-tox-cache",
        restore_hint: "Tox environments can be recreated from project dependencies.",
    },
    ProjectArtifactDefinition {
        directory_name: ".nox",
        rule_id: "windows.project-artifact-nox-cache",
        restore_hint: "Nox environments can be recreated from project dependencies.",
    },
    ProjectArtifactDefinition {
        directory_name: ".ruff_cache",
        rule_id: "windows.project-artifact-ruff-cache",
        restore_hint: "Ruff cache data is rebuildable.",
    },
    ProjectArtifactDefinition {
        directory_name: "__pycache__",
        rule_id: "windows.project-artifact-python-bytecode",
        restore_hint: "Python bytecode cache data is rebuildable.",
    },
    ProjectArtifactDefinition {
        directory_name: ".gradle",
        rule_id: "windows.project-artifact-gradle-cache",
        restore_hint: "Gradle project cache data is rebuildable.",
    },
    ProjectArtifactDefinition {
        directory_name: ".next",
        rule_id: "windows.project-artifact-next-cache",
        restore_hint: "Next.js build output can be regenerated.",
    },
    ProjectArtifactDefinition {
        directory_name: ".nuxt",
        rule_id: "windows.project-artifact-nuxt-cache",
        restore_hint: "Nuxt build output can be regenerated.",
    },
    ProjectArtifactDefinition {
        directory_name: ".output",
        rule_id: "windows.project-artifact-nuxt-output",
        restore_hint: "Nuxt output can be regenerated.",
    },
    ProjectArtifactDefinition {
        directory_name: ".turbo",
        rule_id: "windows.project-artifact-turbo-cache",
        restore_hint: "Turborepo cache data is rebuildable.",
    },
    ProjectArtifactDefinition {
        directory_name: ".parcel-cache",
        rule_id: "windows.project-artifact-parcel-cache",
        restore_hint: "Parcel cache data is rebuildable.",
    },
    ProjectArtifactDefinition {
        directory_name: ".dart_tool",
        rule_id: "windows.project-artifact-dart-tool",
        restore_hint: "Dart and Flutter tool data can be regenerated.",
    },
    ProjectArtifactDefinition {
        directory_name: ".zig-cache",
        rule_id: "windows.project-artifact-zig-cache",
        restore_hint: "Zig cache data is rebuildable.",
    },
    ProjectArtifactDefinition {
        directory_name: "zig-out",
        rule_id: "windows.project-artifact-zig-out",
        restore_hint: "Zig output can be regenerated.",
    },
    ProjectArtifactDefinition {
        directory_name: ".angular",
        rule_id: "windows.project-artifact-angular-cache",
        restore_hint: "Angular cache data is rebuildable.",
    },
    ProjectArtifactDefinition {
        directory_name: ".svelte-kit",
        rule_id: "windows.project-artifact-svelte-kit",
        restore_hint: "SvelteKit build data can be regenerated.",
    },
    ProjectArtifactDefinition {
        directory_name: ".astro",
        rule_id: "windows.project-artifact-astro-cache",
        restore_hint: "Astro build data can be regenerated.",
    },
    ProjectArtifactDefinition {
        directory_name: "coverage",
        rule_id: "windows.project-artifact-coverage",
        restore_hint: "Coverage reports can be regenerated by test tooling.",
    },
    ProjectArtifactDefinition {
        directory_name: "Pods",
        rule_id: "windows.project-artifact-cocoapods",
        restore_hint: "CocoaPods dependencies can be restored with pod install.",
    },
    ProjectArtifactDefinition {
        directory_name: ".cxx",
        rule_id: "windows.project-artifact-cxx-cache",
        restore_hint: "C/C++ build cache data is rebuildable.",
    },
    ProjectArtifactDefinition {
        directory_name: "obj",
        rule_id: "windows.project-artifact-dotnet-obj",
        restore_hint: ".NET object output can be regenerated by the build tool.",
    },
    ProjectArtifactDefinition {
        directory_name: ".expo",
        rule_id: "windows.project-artifact-expo-cache",
        restore_hint: "Expo cache data is rebuildable.",
    },
    ProjectArtifactDefinition {
        directory_name: ".build",
        rule_id: "windows.project-artifact-swift-build",
        restore_hint: "Swift build output can be regenerated.",
    },
];

const PRUNED_SCAN_DIRS: &[&str] = &[
    ".git",
    ".hg",
    ".svn",
    ".trash",
    "$recycle.bin",
    "library",
    "applications",
];

pub fn project_artifact_definitions() -> &'static [ProjectArtifactDefinition] {
    PROJECT_ARTIFACT_DEFINITIONS
}

pub fn project_artifact_definition_for_dir_name(name: &str) -> Option<ProjectArtifactDefinition> {
    PROJECT_ARTIFACT_DEFINITIONS
        .iter()
        .copied()
        .find(|definition| definition.directory_name.eq_ignore_ascii_case(name))
}

pub fn discover_project_artifacts(
    options: &ProjectArtifactScanOptions,
    cancellation: &ScanCancellationToken,
) -> Result<Vec<ProjectArtifactCandidate>> {
    let mut candidates = Vec::new();
    let mut seen_paths = BTreeSet::new();

    for root in &options.roots {
        scan_root(
            root,
            options.max_depth,
            cancellation,
            &mut seen_paths,
            &mut candidates,
        )?;
    }

    candidates.sort_by(|left, right| {
        left.path
            .cmp(&right.path)
            .then_with(|| left.definition.rule_id.cmp(right.definition.rule_id))
    });
    Ok(candidates)
}

pub fn recently_modified_reason(path: &Path, min_age_days: u64) -> Option<String> {
    if min_age_days == 0 || !is_recently_modified(path, min_age_days, SystemTime::now()) {
        return None;
    }

    Some(format!(
        "project artifact was modified within the last {}",
        format_days(min_age_days)
    ))
}

fn is_recently_modified(path: &Path, min_age_days: u64, now: SystemTime) -> bool {
    let Ok(metadata) = fs::symlink_metadata(path) else {
        return false;
    };
    let Ok(modified) = metadata.modified() else {
        return false;
    };

    let age = now.duration_since(modified).unwrap_or(Duration::ZERO);
    age.as_secs() < min_age_days.saturating_mul(24 * 60 * 60)
}

fn format_days(days: u64) -> String {
    if days == 1 {
        "1 day".to_string()
    } else {
        format!("{days} days")
    }
}

fn scan_root(
    root: &Path,
    max_depth: usize,
    cancellation: &ScanCancellationToken,
    seen_paths: &mut BTreeSet<String>,
    candidates: &mut Vec<ProjectArtifactCandidate>,
) -> Result<()> {
    check_cancelled(cancellation)?;

    let metadata = match fs::symlink_metadata(root) {
        Ok(metadata) => metadata,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(err) => return Err(err.into()),
    };

    if !metadata.is_dir() || crate::safety::is_reparse_like(&metadata) {
        return Ok(());
    }

    let mut pending = VecDeque::from([(root.to_path_buf(), 0_usize)]);
    while let Some((dir, depth)) = pending.pop_front() {
        check_cancelled(cancellation)?;

        if let Some(name) = dir.file_name().and_then(|name| name.to_str()) {
            if let Some(definition) = project_artifact_definition_for_dir_name(name) {
                push_candidate(definition, dir, seen_paths, candidates);
                continue;
            }

            if should_prune_scan_dir(name) {
                continue;
            }
        }

        if depth >= max_depth {
            continue;
        }

        let entries = match fs::read_dir(&dir) {
            Ok(entries) => entries,
            Err(err) => {
                tracing::debug!(
                    path = %dir.display(),
                    error = %err,
                    "project artifact directory read skipped"
                );
                continue;
            }
        };
        let mut child_dirs = Vec::new();

        for entry in entries {
            let entry = match entry {
                Ok(entry) => entry,
                Err(err) => {
                    tracing::debug!(
                        path = %dir.display(),
                        error = %err,
                        "project artifact directory entry skipped"
                    );
                    continue;
                }
            };
            let path = entry.path();
            let metadata = match fs::symlink_metadata(&path) {
                Ok(metadata) => metadata,
                Err(err) => {
                    tracing::debug!(
                        path = %path.display(),
                        error = %err,
                        "project artifact metadata read skipped"
                    );
                    continue;
                }
            };

            if metadata.is_dir() && !crate::safety::is_reparse_like(&metadata) {
                child_dirs.push(path);
            }
        }

        child_dirs.sort();
        for child in child_dirs {
            pending.push_back((child, depth.saturating_add(1)));
        }
    }

    Ok(())
}

fn push_candidate(
    definition: ProjectArtifactDefinition,
    path: PathBuf,
    seen_paths: &mut BTreeSet<String>,
    candidates: &mut Vec<ProjectArtifactCandidate>,
) {
    let key = path.as_os_str().to_string_lossy().replace('\\', "/");
    if seen_paths.insert(key.to_ascii_lowercase()) {
        candidates.push(ProjectArtifactCandidate { definition, path });
    }
}

fn should_prune_scan_dir(name: &str) -> bool {
    PRUNED_SCAN_DIRS
        .iter()
        .any(|pruned| pruned.eq_ignore_ascii_case(name))
}

fn check_cancelled(cancellation: &ScanCancellationToken) -> Result<()> {
    if cancellation.is_cancelled() {
        return Err(RebeccaError::OperationCancelled(
            "project artifact scan was cancelled".to_string(),
        ));
    }

    Ok(())
}
