use super::ProjectArtifactDefinition;

#[derive(Debug, Clone, Copy)]
pub(super) struct ProjectArtifactRule {
    pub(super) definition: ProjectArtifactDefinition,
    pub(super) context: ProjectArtifactContext,
}

#[derive(Debug, Clone, Copy)]
pub(super) enum ProjectArtifactContext {
    NodeProject,
    TargetProject,
    PythonProject,
    PythonCache,
    GradleProject,
    DartProject,
    ZigProject,
    GenericProjectOutput,
    CocoapodsProject,
    CxxProject,
    ExpoProject,
    SwiftPackage,
    DotnetBin,
    DotnetObj,
    ComposerVendor,
}

const fn artifact_rule(
    directory_name: &'static str,
    rule_id: &'static str,
    restore_hint: &'static str,
    context: ProjectArtifactContext,
) -> ProjectArtifactRule {
    ProjectArtifactRule {
        definition: ProjectArtifactDefinition {
            directory_name,
            rule_id,
            restore_hint,
        },
        context,
    }
}

pub(super) const PROJECT_ARTIFACT_RULES: &[ProjectArtifactRule] = &[
    artifact_rule(
        "node_modules",
        "windows.project-artifact-node-modules",
        "Dependencies can be restored with the project's package manager.",
        ProjectArtifactContext::NodeProject,
    ),
    artifact_rule(
        "target",
        "windows.project-artifact-target",
        "Build outputs can be regenerated by the project build tool.",
        ProjectArtifactContext::TargetProject,
    ),
    artifact_rule(
        "build",
        "windows.project-artifact-build",
        "Build outputs can be regenerated by the project build tool.",
        ProjectArtifactContext::GenericProjectOutput,
    ),
    artifact_rule(
        "dist",
        "windows.project-artifact-dist",
        "Distribution outputs can be regenerated by the project build tool.",
        ProjectArtifactContext::GenericProjectOutput,
    ),
    artifact_rule(
        "venv",
        "windows.project-artifact-python-venv",
        "Python virtual environments can be recreated from project dependencies.",
        ProjectArtifactContext::PythonProject,
    ),
    artifact_rule(
        ".venv",
        "windows.project-artifact-python-venv",
        "Python virtual environments can be recreated from project dependencies.",
        ProjectArtifactContext::PythonProject,
    ),
    artifact_rule(
        ".pytest_cache",
        "windows.project-artifact-pytest-cache",
        "Pytest cache data is rebuildable.",
        ProjectArtifactContext::PythonProject,
    ),
    artifact_rule(
        ".mypy_cache",
        "windows.project-artifact-mypy-cache",
        "Mypy cache data is rebuildable.",
        ProjectArtifactContext::PythonProject,
    ),
    artifact_rule(
        ".tox",
        "windows.project-artifact-tox-cache",
        "Tox environments can be recreated from project dependencies.",
        ProjectArtifactContext::PythonProject,
    ),
    artifact_rule(
        ".nox",
        "windows.project-artifact-nox-cache",
        "Nox environments can be recreated from project dependencies.",
        ProjectArtifactContext::PythonProject,
    ),
    artifact_rule(
        ".ruff_cache",
        "windows.project-artifact-ruff-cache",
        "Ruff cache data is rebuildable.",
        ProjectArtifactContext::PythonProject,
    ),
    artifact_rule(
        "__pycache__",
        "windows.project-artifact-python-bytecode",
        "Python bytecode cache data is rebuildable.",
        ProjectArtifactContext::PythonCache,
    ),
    artifact_rule(
        ".gradle",
        "windows.project-artifact-gradle-cache",
        "Gradle project cache data is rebuildable.",
        ProjectArtifactContext::GradleProject,
    ),
    artifact_rule(
        ".next",
        "windows.project-artifact-next-cache",
        "Next.js build output can be regenerated.",
        ProjectArtifactContext::NodeProject,
    ),
    artifact_rule(
        ".nuxt",
        "windows.project-artifact-nuxt-cache",
        "Nuxt build output can be regenerated.",
        ProjectArtifactContext::NodeProject,
    ),
    artifact_rule(
        ".output",
        "windows.project-artifact-nuxt-output",
        "Nuxt output can be regenerated.",
        ProjectArtifactContext::NodeProject,
    ),
    artifact_rule(
        ".turbo",
        "windows.project-artifact-turbo-cache",
        "Turborepo cache data is rebuildable.",
        ProjectArtifactContext::NodeProject,
    ),
    artifact_rule(
        ".parcel-cache",
        "windows.project-artifact-parcel-cache",
        "Parcel cache data is rebuildable.",
        ProjectArtifactContext::NodeProject,
    ),
    artifact_rule(
        ".dart_tool",
        "windows.project-artifact-dart-tool",
        "Dart and Flutter tool data can be regenerated.",
        ProjectArtifactContext::DartProject,
    ),
    artifact_rule(
        ".zig-cache",
        "windows.project-artifact-zig-cache",
        "Zig cache data is rebuildable.",
        ProjectArtifactContext::ZigProject,
    ),
    artifact_rule(
        "zig-out",
        "windows.project-artifact-zig-out",
        "Zig output can be regenerated.",
        ProjectArtifactContext::ZigProject,
    ),
    artifact_rule(
        ".angular",
        "windows.project-artifact-angular-cache",
        "Angular cache data is rebuildable.",
        ProjectArtifactContext::NodeProject,
    ),
    artifact_rule(
        ".svelte-kit",
        "windows.project-artifact-svelte-kit",
        "SvelteKit build data can be regenerated.",
        ProjectArtifactContext::NodeProject,
    ),
    artifact_rule(
        ".astro",
        "windows.project-artifact-astro-cache",
        "Astro build data can be regenerated.",
        ProjectArtifactContext::NodeProject,
    ),
    artifact_rule(
        "coverage",
        "windows.project-artifact-coverage",
        "Coverage reports can be regenerated by test tooling.",
        ProjectArtifactContext::GenericProjectOutput,
    ),
    artifact_rule(
        "bin",
        "windows.project-artifact-dotnet-bin",
        ".NET bin outputs can be regenerated by the project build tool.",
        ProjectArtifactContext::DotnetBin,
    ),
    artifact_rule(
        "obj",
        "windows.project-artifact-dotnet-obj",
        ".NET object output can be regenerated by the build tool.",
        ProjectArtifactContext::DotnetObj,
    ),
    artifact_rule(
        "vendor",
        "windows.project-artifact-composer-vendor",
        "Composer vendor dependencies can be restored with composer install.",
        ProjectArtifactContext::ComposerVendor,
    ),
    artifact_rule(
        "Pods",
        "windows.project-artifact-cocoapods",
        "CocoaPods dependencies can be restored with pod install.",
        ProjectArtifactContext::CocoapodsProject,
    ),
    artifact_rule(
        ".cxx",
        "windows.project-artifact-cxx-cache",
        "C/C++ build cache data is rebuildable.",
        ProjectArtifactContext::CxxProject,
    ),
    artifact_rule(
        ".expo",
        "windows.project-artifact-expo-cache",
        "Expo cache data is rebuildable.",
        ProjectArtifactContext::ExpoProject,
    ),
    artifact_rule(
        ".build",
        "windows.project-artifact-swift-build",
        "Swift build output can be regenerated.",
        ProjectArtifactContext::SwiftPackage,
    ),
];

pub(super) const CACHEDIR_TAG_DEFINITION: ProjectArtifactDefinition = ProjectArtifactDefinition {
    directory_name: "CACHEDIR.TAG",
    rule_id: "windows.project-artifact-cachedir-tag",
    restore_hint: "CACHEDIR.TAG marks this directory as rebuildable cache data.",
};
